language: rust

cache: cargo

os:
  - linux

rust:
  - stable
  - beta
  - nightly

before_script:
  - rustup component add clippy-preview

script:
  - cargo test --verbose
  - cargo clippy -- -D warnings

matrix:
  allow_failures:
    - rust: nightly
